version: '2'
services:
  db:
    container_name: db
    image: mysql
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=True"
    ports:
      - "3306:3306"
    volumes:
      - "./docker/data:/docker-entrypoint-initdb.d"
    working_dir: "/docker-entrypoint-initdb.d"

  drchrono:
    container_name: drchrono
    image: drchrono
    env_file:
      - "docker/environment"
    ports:
      - "8080:8080"
#    command: /bin/bash -c "while true; do echo mark; sleep 2; done"
    command: "python ./manage.py runserver 0.0.0.0:8080"
    volumes:
      - ".:/usr/src/app"
    working_dir: /usr/src/app
    depends_on:
      - "db"
    build:
      context: .
      dockerfile: ./docker/drchrono-dockerfile